version: '2'

# 3 node cluster
# If you see exit code 137 (OOM killer) then ensure Docker has access to more resources
services:
  cassandra-node-0:
    container_name: cassandra-node-0
    image: cassandra:3.11.0
    ports:
      - "9042:9042"   # Native transport
      - "7199:7199"   # JMX
      - "9160:9160"   # Thrift clients
    volumes:
        - ../../TPs:/TPs

  cassandra-node-1:
    container_name: cassandra-node-1
    image: cassandra:3.11.0
    command: /bin/bash -c "echo 'Waiting for node 0 (seed)' && sleep 15 && /docker-entrypoint.sh cassandra -f"
    volumes:
        - ../../TPs:/TPs
    environment:
      - "CASSANDRA_SEEDS=cassandra-node-0"
    depends_on:
      - "cassandra-node-0"

  # you cannot have multiple nodes join the cluster at the same time when
  # cassandra.consistent.rangemovement is true so we further delay it to give it time to stabilize
  cassandra-node-2:
    container_name: cassandra-node-2
    image: cassandra:3.11.0
    command: /bin/bash -c "echo 'Waiting for node 0 (seed)' && sleep 40 && /docker-entrypoint.sh cassandra -f"
    volumes:
        - ../../TPs:/TPs
    environment:
      - "CASSANDRA_SEEDS=cassandra-node-0"
    depends_on:
      - "cassandra-node-0"
